version: '3.8'

services:
  # 🚀 Aplicação Laravel
  rapidex.test:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: rapidex_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - './src:/var/www/html'
      - './docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini'
    networks:
      - rapidex_network
    depends_on:
      - mysql
      - redis
    environment:
      APP_ENV: local
      APP_NAME: Rapidex
      APP_DEBUG: true
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: rapidex_db
      DB_USERNAME: rapidex_user
      DB_PASSWORD: rapidex123
      REDIS_HOST: redis
      REDIS_PORT: 6379
      QUEUE_CONNECTION: redis
      BROADCAST_DRIVER: pusher
      MAIL_MAILER: smtp
      MAIL_HOST: mailhog
      MAIL_PORT: 1025

  # 🌐 Nginx
  nginx:
    image: nginx:alpine
    container_name: rapidex_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './src:/var/www/html'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    networks:
      - rapidex_network
    depends_on:
      - rapidex.test

  # 🗄️ MySQL
  mysql:
    image: mysql:8.0
    container_name: rapidex_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: rapidex_db
      MYSQL_USER: rapidex_user
      MYSQL_PASSWORD: rapidex123
      MYSQL_ALLOW_EMPTY_PASSWORD: 0
    volumes:
      - mysql_data:/var/lib/mysql
      - './docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf'
    networks:
      - rapidex_network
    command: --default-authentication-plugin=mysql_native_password

  # 🔴 Redis
  redis:
    image: redis:7-alpine
    container_name: rapidex_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - './docker/redis/redis.conf:/etc/redis/redis.conf'
    networks:
      - rapidex_network
    command: redis-server /etc/redis/redis.conf --appendonly yes

  # 🔍 Meilisearch
  meilisearch:
    image: getmeili/meilisearch:v1.5
    container_name: rapidex_search
    restart: unless-stopped
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: rapidex_search_master_key_2024
      MEILI_ENV: development
      MEILI_HTTP_ADDR: 0.0.0.0:7700
    volumes:
      - meilisearch_data:/meili_data
    networks:
      - rapidex_network

  # 📊 Laravel Horizon
  horizon:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: rapidex_horizon
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - './src:/var/www/html'
    networks:
      - rapidex_network
    depends_on:
      - mysql
      - redis
      - rapidex.test
    environment:
      APP_ENV: local
      CONTAINER_ROLE: horizon
    command: php artisan horizon

  # ⚡ Queue Worker
  queue-worker:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: rapidex_queue
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - './src:/var/www/html'
    networks:
      - rapidex_network
    depends_on:
      - mysql
      - redis
      - rapidex.test
    environment:
      APP_ENV: local
      CONTAINER_ROLE: queue
    command: php artisan queue:work redis --sleep=3 --tries=3 --max-time=3600

  # ⏰ Scheduler
  scheduler:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: rapidex_scheduler
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - './src:/var/www/html'
    networks:
      - rapidex_network
    depends_on:
      - mysql
      - redis
      - rapidex.test
    environment:
      APP_ENV: local
      CONTAINER_ROLE: scheduler
    command: php artisan schedule:work

  # 📧 MailHog
  mailhog:
    image: mailhog/mailhog:latest
    container_name: rapidex_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - rapidex_network

networks:
  rapidex_network:
    driver: bridge
    name: rapidex_network

volumes:
  mysql_data:
    name: rapidex_mysql_data
  redis_data:
    name: rapidex_redis_data
  meilisearch_data:
    name: rapidex_search_data
